config/routes.rb
Rails.application.routes.draw do
  # resources :restaurants
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
 <%= form_for @task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Cooking' %>
  </div>

  <div>
    <%= f.label :details %>
    <%= f.text_field :details, placeholder: 'carrots' %>
  </div>

  <%= f.submit %>
 <% end %>

app/views/tasks/index.html.erb
  <h1>Task List</h1>
  <% @tasks.each do |task| %>

  <h3><%= task.id %> - <%= task.title %> </h3>
  <%= link_to "🔍 More", task_path(task) %>
  <%= link_to "🔧 Edit", edit_task_path(task) %>
  <%= link_to "🗑 Delete", task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
  <% end %>

  <h3><%=link_to "➕ Add", tasks_new_path(@tasks) %></h3>

app/views/tasks/new.html.erb
<h1>Add Task to List</h1>


 <%= form_for @task do |task| %>
  <div>
    <%= task.label :title %>
    <%= task.text_field :title, placeholder: 'Cooking' %>
  </div>

  <div>
    <%= task.label :details %>
    <%= task.text_field :details, placeholder: "Buying groceries" %>
  </div>

  <%= task.submit "Submit" %>
 <% end %>

app/views/tasks/show.html.erb
  <h1>Task List - Details</h1>
  <h3><%= @task.id %> - <%= @task.title %> </h3>
  <p>Details: <%= @task.details %> </p>

  <p>
  <%= link_to "Go back", tasks_path(@tasks) %>
  <%= link_to "Edit", edit_task_path(@task) %>
</p>